name: terraform-plan
description: Create a terraform plan
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false
  variables:
    description: Variable definitions
    required: false
  var:
    description: Comma separated list of vars to set, e.g. 'foo=bar'
    required: false
    deprecationMessage: Use the variables input instead.
  var_file:
    description: List of var file paths, one per line
    required: false
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: 0
  label:
    description: A friendly name for this plan
    required: false
    default: ""
  add_github_comment:
    description: Add the plan to a GitHub PR
    required: false
    default: true
  lock_during_plan:
    description: Specify whether the state should be locked during terraform plan
    required: false
    default: true

outputs:
  changes:
    description: If the generated plan would update any resources or outputs this is set to `true`, otherwise it's set to `false`.
  text_plan_path:
    description: Path to a file in the workspace containing the generated plan in human readble format.
  json_plan_path:
    description: Path to a file in the workspace containing the generated plan in JSON format. This won't be set if the backend type is `remote`.

runs:
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/plan.sh

branding:
  icon: globe
  color: purple
