name: tofu-plan
description: Create an OpenTofu plan
author: Daniel Flook

inputs:
  path:
    description: The path to the OpenTofu root module to generate a plan for.
    required: false
    default: "."
  workspace:
    description: OpenTofu workspace to run the plan for.
    required: false
    default: "default"
  label:
    description: |
      A friendly name for the environment the OpenTofu configuration is for.
      This will be used in the PR comment for easy identification.

      If this is set, it must be the same as the `label` used in any corresponding [`dflook/tofu-apply`](https://github.com/dflook/terraform-github-actions/tree/main/tofu-apply) action.
    required: false
    default: ""
  variables:
    description: |
      Variables to set for the tofu plan. This should be valid OpenTofu syntax - like a [variable definition file](https://opentofu.org/docs/language/values/variables/#variable-definitions-tfvars-files).

      Variables set here override any given in `var_file`s.
    required: false
  var_file:
    description: |
      List of tfvars files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
    required: false
  var:
    description: |
      Comma separated list of OpenTofu vars to set.
      This is deprecated due to the following limitations:
      - Only primitive types can be set with `var` - number, bool and string.
      - String values may not contain a comma.
      - Values set with `var` will be overridden by values contained in `var_file`s
      - Does not work with the `remote` backend
      You can change from `var` to `variables` by putting each variable on a separate line and ensuring each string value is quoted.
    required: false
    deprecationMessage: Use the variables input instead.
  backend_config:
    description: List of OpenTofu backend config values, one per line.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of OpenTofu backend config files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
    required: false
    default: ""
  replace:
    description: List of resources to replace, one per line.
    required: false
    default: ""
  target:
    description: |
      List of resources to apply, one per line.
      The plan will be limited to these resources and their dependencies.
    required: false
    default: ""
  destroy:
    description: |
      Set to `true` to generate a plan to destroy all resources.

      This generates a plan in [destroy mode](https://opentofu.org/docs/cli/commands/plan/#planning-modes).
    required: false
    default: "false"
  add_github_comment:
    description: |
      Controls whether a comment is added to the PR with the generated plan.

      The default is `true`, which adds a comment to the PR with the results of the plan.
      Set to `changes-only` to add a comment only when the plan indicates there are changes to apply.
      Set to `always-new` to always create a new comment for each plan, instead of updating the previous comment.
      Set to `false` to disable the comment - the plan will still appear in the workflow log.
    required: false
    default: "true"
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: "0"
  refresh:
    description: Skip checking for external changes to remote objects while creating the plan
    required: false
    default: "true"

outputs:
  changes:
    description: Set to 'true' if the plan would apply any changes, 'false' if it wouldn't.
  plan_path:
    description: |
      This is the path to the generated plan in an opaque binary format.
      The path is relative to the Actions workspace.

      The plan can be used as the `plan_file` input to the [dflook/tofu-apply](https://github.com/dflook/terraform-github-actions/tree/main/tofu-apply) action.

      OpenTofu plans often contain sensitive information, so this output should be treated with care.
  json_plan_path:
    description: |
      This is the path to the generated plan in [JSON Output Format](https://opentofu.org/docs/internals/json-format/).
      The path is relative to the Actions workspace.

      OpenTofu plans often contain sensitive information, so this output should be treated with care.
  text_plan_path:
    description: |
      This is the path to the generated plan in a human-readable format.
      The path is relative to the Actions workspace.
  to_add:
    description: The number of resources that would be affected by this operation.
  to_change:
    description: The number of resources that would be affected by this operation.
  to_destroy:
    description: The number of resources that would be affected by this operation.
  to_move:
    description: The number of resources that would be affected by this operation.
  to_import:
    description: The number of resources that would be affected by this operation.
  run_id:
    description: If the root module uses the `remote` or `cloud` backend in remote execution mode, this output will be set to the remote run id.

runs:
  env:
    OPENTOFU: true
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/plan.sh

branding:
  icon: globe
  color: purple
