name: tofu-new-workspace
description: Creates a new OpenTofu workspace. If the workspace already exists, succeeds without doing anything.
author: Daniel Flook

inputs:
  path:
    description: The path to the OpenTofu root module directory.
    required: false
    default: "."
  workspace:
    description: The name of the OpenTofu workspace to create.
    required: true
  variables:
    description: |
      Variables to set when initializing OpenTofu. This should be valid OpenTofu syntax - like a [variable definition file](https://opentofu.org/docs/language/values/variables/#variable-definitions-tfvars-files).

      Variables set here override any given in `var_file`s.
    required: false
  var_file:
    description: |
      List of tfvars files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
    required: false
  backend_config:
    description: List of OpenTofu backend config values, one per line.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of OpenTofu backend config files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
    required: false
    default: ""

runs:
  env:
    OPENTOFU: true
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/new-workspace.sh

branding:
  icon: globe
  color: purple
