name: tofu-fmt-check
description: Check that OpenTofu configuration files are in canonical format
author: Daniel Flook

inputs:
  path:
    description: The path containing OpenTofu files to check the formatting of.
    required: false
    default: "."
  workspace:
    description: |
      OpenTofu workspace to inspect when discovering the OpenTofu version to use, if the version is not otherwise specified.
      See [dflook/tofu-version](https://github.com/dflook/terraform-github-actions/tree/main/tofu-version#tofu-version-action) for details.
    required: false
    default: "default"
  variables:
    description: |
      Variables to set when initializing OpenTofu. This should be valid OpenTofu syntax - like a [variable definition file](https://opentofu.org/docs/language/values/variables/#variable-definitions-tfvars-files).
      Variables set here override any given in `var_file`s.
    required: false
  var_file:
    description: |
      List of tfvars files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
    required: false
  backend_config:
    description: |
      List of OpenTofu backend config values, one per line. This is used for discovering the OpenTofu version to use, if the version is not otherwise specified.
      See [dflook/tofu-version](https://github.com/dflook/terraform-github-actions/tree/main/tofu-version#tofu-version-action) for details.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of OpenTofu backend config files to use, one per line. This is used for discovering the OpenTofu version to use, if the version is not otherwise specified.
      See [dflook/tofu-version](https://github.com/dflook/terraform-github-actions/tree/main/tofu-version#tofu-version-action) for details.
      Paths should be relative to the GitHub Actions workspace
    required: false
    default: ""

outputs:
  failure-reason:
    description: |
      When the job outcome is `failure` because the format check failed, this will be set to 'check-failed'.
      If the job fails for any other reason this will not be set.
      This can be used with the Actions expression syntax to conditionally run a step when the format check fails.

runs:
  env:
    OPENTOFU: true
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/fmt-check.sh

branding:
  icon: globe
  color: purple
