name: terraform-state
description: Inspect terraform state
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false

outputs:
  state_list_path:
    description: Path to a file in the workspace containing a list of terraform resources in the state
  state_json_path:
    description: Path to a file in the workspace containing the terraform state in JSON format

runs:
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/state.sh

branding:
  icon: globe
  color: purple
