name: tofu-remote-state
description: Retrieves the root-level outputs from an OpenTofu remote state.
author: Daniel Flook

inputs:
  backend_type:
    description: The name of the OpenTofu plugin used for backend state
    required: true
  workspace:
    description: OpenTofu workspace to get the outputs for
    required: false
    default: "default"
  backend_config:
    description: List of OpenTofu backend config values, one per line.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of OpenTofu backend config files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
    required: false
    default: ""

outputs:
  json_output_path:
    description: |
      This is the path to all the root module outputs in a JSON file.
      The path is relative to the Actions workspace.

      For example, with the OpenTofu config:

      ```hcl
      output "service_hostname" {
        value = "example.com"
      }
      ```

      The file pointed to by this output will contain:

      ```json
      {
        "service_hostname": "example.com"
      }
      ```

      OpenTofu list, set and tuple types are cast to a JSON array, map and object types are cast to a JSON object.

runs:
  env:
    OPENTOFU: true
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/remote-state.sh

branding:
  icon: globe
  color: purple
