from action import Input

plan_path = Input(
    name='plan_path',
    type='string',
    description='''
Path to a plan file to apply. This would have been generated by a previous [`dflook/$ToolName-plan`](https://github.com/dflook/terraform-github-actions/tree/main/$ToolName-plan) action.

The default behaviour when this is not set is to generate a plan from the current configuration and compare it to the plan attached to the PR comment.
If it is logically the same, the plan will be applied.

When this is set to a plan file, the plan will not be generated again. If it is the exact same plan as the one attached to the PR comment, it will be applied.
This will be faster than generating a new plan.

There are downsides to applying a stored plan:

- The plan may contain sensitive information so must be stored securely, possibly outside of GitHub.
- It does not account for any changes that have occurred since it was generated, and may no longer be correct.
- Plans must be generated and applied in strict order. Multiple open PRs will cause conflicts if they are applied out of order.
- Plans are not portable between platforms.
- $ProductName and provider versions must match between the plan generation and apply.

When `auto_approve` is set to `true`, the plan will be applied without checking if it is the same as the one attached to the PR comment.
''',
    required=False,
    default=''
)
