name: terraform-check
description: Check if there are terraform changes to apply
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: true
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: Comma separated list of backend configs to set, e.g. 'foo=bar'
    required: false
  backend_config_file:
    description: Path to a backend config file"
    required: false
  variables:
    description: Variable definitions
    required: false
  var:
    description: Comma separated list of vars to set, e.g. 'foo=bar'
    required: false
    deprecationMessage: Use the variables input instead.
  var_file:
    description: Comma separated list of var file paths
    required: false
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: 0
  run:
    description: Executes these shell commands before running terraform
    required: false

runs:
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/check.sh

branding:
  icon: globe
  color: purple
