name: tofu-unlock-state
description: Force unlocks an OpenTofu remote state.
author: Daniel Flook

inputs:
  path:
    description: Path to the OpenTofu root module that defines the remote state to unlock
    required: false
    default: "."
  workspace:
    description: OpenTofu workspace to unlock the remote state for
    required: false
    default: "default"
  backend_config:
    description: List of OpenTofu backend config values, one per line.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of OpenTofu backend config files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
    required: false
    default: ""
  lock_id:
    description: The ID of the state lock to release.
    required: true

runs:
  env:
    OPENTOFU: true
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/unlock-state.sh

branding:
  icon: globe
  color: purple
