name: Test workflow command supression

on:
  - pull_request

jobs:
  workflow_command_injection:
    runs-on: ubuntu-latest
    name: Plan with workflow command injection
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Plan
        uses: ./terraform-plan
        id: plan
        with:
          path: tests/workflows/test-workflow-commands
          add_github_comment: false
        env:
          TERRAFORM_PRE_RUN: |
            echo "::set-output name=output_string::strawberry"

      - name: Verify outputs
        run: |
          if [[ -n "${{ steps.plan.outputs.output_string }}" ]]; then
            echo "::error:: output_string should not have been set"
            exit 1
          fi
