FROM golang:1.12.6 AS tfmask

RUN git clone https://github.com/cloudposse/tfmask.git \
 && cd tfmask \
 && git checkout 9a15f421210397f2c321a57b5ed3d108a012a86d \
 && make \
 && make go/build

FROM debian:bullseye-slim AS terraform-github-actions-base

# Terraform environment variables
ENV CHECKPOINT_DISABLE=true
ENV TF_IN_AUTOMATION=true
ENV TF_INPUT=false
ENV TF_PLUGIN_CACHE_DIR=/usr/local/share/terraform/plugin-cache

RUN <<EOF
 apt-get update
 apt-get install --no-install-recommends -y \
    git \
    ssh \
    tar \
    gzip \
    ca-certificates \
    curl \
    unzip \
    jq \
    python3 \
    python3-requests \
    python3-pip \
    wget \
    gpg \
    gpg-agent \
    dirmngr \
    tree
 rm -rf /var/lib/apt/lists/*

 mkdir -p $TF_PLUGIN_CACHE_DIR

 gpg --recv-keys C874011F0AB405110D02105534365D9472D7468F
 echo "C874011F0AB405110D02105534365D9472D7468F:6:" | gpg --import-ownertrust

 curl https://get.opentofu.org/opentofu.gpg | gpg --import
 echo "E3E6E43D84CB852EADB0051D0C0AF313E5FD9F80:6:" | gpg --import-ownertrust

 gpg --check-trustdb

 echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
 echo "IdentityFile /.ssh/id_rsa" >> /etc/ssh/ssh_config
 mkdir -p /.ssh
EOF

COPY --from=tfmask /go/tfmask/release/tfmask /usr/local/bin/tfmask
ENV TFMASK_RESOURCES_REGEX="(?i)^(random_id|kubernetes_secret|acme_certificate).*$"
